drop the md5sum test too

diff --git a/tests/source/dotest b/tests/source/dotest
--- a/tests/source/dotest
+++ b/tests/source/dotest
@@ -99,17 +99,17 @@ find ../.. '(' -name '*.c' -o -name '*.h' ')' -print0 | xargs -0 \
 testit src.style
 
 
-# Stupid BSD makes us check for this..
-if [ $(type -P md5sum) != "" ]; then
-	for x in $(find ../.. '(' -name '*.c' -o -name '*.h' ')' ); do
-		./space "$x" > "$x~"
-		if ! diff -u "$x" "$x~" ; then
-			echo "New file: $x~"
-		else
-			rm -f "$x~"
-		fi
-	done > src.space
-	testit src.space
-fi
+#
+# Auto clean up the space issues
+#
+for x in $(find ../.. '(' -name '*.c' -o -name '*.h' ')' ); do
+	./space "$x" > "$x~"
+	if ! diff -u "$x" "$x~" ; then
+		echo "New file: $x~"
+	else
+		rm -f "$x~"
+	fi
+done > src.space
+testit src.space
 
 exit ${ret}
